import re
from playwright.sync_api import Page, expect


def test_example(page: Page) -> None:
    page.goto("https://opensource-demo.orangehrmlive.com/web/index.php/auth/login")
    page.get_by_role("textbox", name="Username").click()
    page.get_by_role("textbox", name="Username").fill("Admin")
    page.locator("div").filter(has_text=re.compile(r"^Password$")).nth(2).click()
    page.get_by_role("textbox", name="Password").click()
    page.get_by_role("textbox", name="Password").fill("admin123")
    page.get_by_role("button", name="Login").click()
    page.get_by_role("link", name="Claim").click()
    page.get_by_role("button", name=" Assign Claim").click()
    page.get_by_role("textbox", name="Type for hints...").click()
    page.get_by_role("textbox", name="Type for hints...").fill("rav")
    page.get_by_text("Ravi M Bbala kumar ravi").click()
    page.get_by_text("-- Select --").first.click()
    page.get_by_role("option", name="Accommodation").click()
    page.locator("div").filter(has_text=re.compile(r"^-- Select --$")).nth(2).click()
    page.get_by_role("option", name="Indian Rupee").click()
    expect(page.locator("textarea")).to_be_visible()
    page.locator("textarea").click()
    page.locator("textarea").fill("area")
    expect(page.get_by_role("button", name="Create")).to_be_visible()
    page.get_by_role("button", name="Create").click()
    page.locator(".oxd-icon.bi-check").first.click()
    page.get_by_role("button", name=" Add").first.click()
    page.locator("div").filter(has_text=re.compile(r"^Expense Type-- Select --$")).nth(2).click()
    page.get_by_role("option", name="Accommodation").click()
    page.locator(".oxd-icon.bi-calendar").click()
    page.get_by_text("15").click()
    expect(page.locator("div").filter(has_text=re.compile(r"^Amount$")).nth(1)).to_be_visible()
    page.locator(".oxd-grid-2 > div:nth-child(2) > .oxd-input-group > div:nth-child(2) > .oxd-input").click()
    page.locator(".oxd-input.oxd-input--focus").fill("1000")
    expect(page.get_by_role("button", name="Save")).to_be_visible()
    expect(page.get_by_role("dialog").locator("textarea")).to_be_visible()
    page.get_by_role("dialog").locator("textarea").click()
    page.get_by_role("dialog").locator("textarea").fill("hello")
    page.get_by_role("dialog").locator("textarea").click()
    expect(page.get_by_role("dialog").locator("textarea")).to_be_visible()
    page.get_by_role("button", name="Save").click()
